{% extends 'text.swig' %}

{% block body %}
<div>
  <h2 >About this site</h2>
  
  <h3 >Built with <a href="http://gruntjs.com">Grunt</a>:</h3>
  <ul>
    <li><a href="http://lesscss.org/">LESS</a></li>
    <li><a href="">SWIG</a> templating</li>
    <li><a href="http://developer.yahoo.com/yui/compressor/">YUI compressor</a></li>
  </ul>

  <h3>Libraries &amp; plugins:</h3>
  <ul>
    <li><a href="https://github.com/necolas/normalize.css/">normalize.css</a></li>
    <li><a href="http://jquery.com/">jQuery</a></li>
    <li><a href="http://raphaeljs.com/">Raphaël</a></li>
    <li><a href="http://kolber.github.com/audiojs/">audio.js</a></li>
    <li><a href="http://modernizr.com/">Modernizr</a></li>
    <li><a href="http://code.google.com/p/swfobject/">SWFObject</a></li>
    <li><a href="http://cherne.net/brian/resources/jquery.hoverIntent.html">hover intent</a></li>
    <li><a href="http://www.kelvinluck.com/assets/jquery/jScrollPane/jScrollPane.html">jScrollPane</a></li>
    <li><a href="http://brandonaaron.net/code/mousewheel/docs">mouse wheel</a></li>
  </ul>

  <h3 >Social media content:</h3>
  <ul>
    <li><a href="http://vimeo.com/">vimeo</a></li>
    <li><a href="http://www.flickr.com/">flickr</a></li>
  </ul>

  <h3>©2013 Pete Schirmer. All Rights Reserved.</h3>
</div>
{% endblock%}