{% extends 'text.swig' %}

{% block body %}
<div>
  <h2 >About this site</h2>
  
  <h3 >Built with <a href="http://gruntjs.com">Grunt</a> (<a href="http://nodejs.org/">Node.js</a>):</h3>
  <ul>
    <li><a href="http://lesscss.org/">LESS</a></li>
    <li><a href="http://paularmstrong.github.io/swig/">SWIG</a> templating</li>
    <li><a href="http://developer.yahoo.com/yui/compressor/">YUI compressor</a></li>
  </ul>

  <h3>Libraries &amp; plugins:</h3>
  <ul>
    <li><a href="https://github.com/necolas/normalize.css/">normalize.css</a></li>
    <li><a href="http://jquery.com/">jQuery</a></li>
    <li><a href="http://raphaeljs.com/">Raphaël</a></li>
    <li><a href="http://kolber.github.com/audiojs/">audio.js</a></li>
    <li><a href="http://modernizr.com/">Modernizr</a></li>
    <li><a href="http://code.google.com/p/swfobject/">SWFObject</a></li>
    <li><a href="http://cherne.net/brian/resources/jquery.hoverIntent.html">hover intent</a></li>
    <li><a href="http://www.kelvinluck.com/assets/jquery/jScrollPane/jScrollPane.html">jScrollPane</a></li>
    <li><a href="http://brandonaaron.net/code/mousewheel/docs">mouse wheel</a></li>
  </ul>

  <h3>Hosted assets:</h3>
  <ul>
    <li><a href="http://vimeo.com/">vimeo</a></li>
    <li><a href="http://www.flickr.com/">flickr</a></li>
  	<li>Google <a href="http://www.google.com/fonts/">fonts</a> & <a href="https://developers.google.com/speed/libraries/devguide">hosted code libraries</a></li>
  	<li><a href="http://cdnjs.com/">cdnjs</a></li>
  </ul>
  <h3>Source:</h3>
  <ul>
  	<li><a href="https://github.com/thisispete/thisispete">Github</a></li>
  </ul>
  
  <h3>©2013 Pete Schirmer. All Rights Reserved.</h3>
</div>
{% endblock%}