{% extends 'img.swig' %}
{% block body%}
  <p>This is my workbench. I designed it in fusion 360, then while sourcing materials found this beautiful Afzelia and Chinkopin wood from a lumber yard near my house in Oakland that was closing. I modified the legs and did bridle joints instead of just layering them as in the design. Found some nice vintage drawer pulls, and topped with some masonite.</p>
{% endblock %}