{% extends 'img.swig' %}
{% block body%}
  <p>When I was living in my loft in San Francisco I was short on long-term storage. I sketched up this platform bed with storage under the mattress and commissioned <a href="http://jeremiahcollection.com/">Jeremiah Collection</a> to manufacture it for me out of walnut. They added the headboard, modified a few details to conceal all the hardware, it came out amazing!</p>
{% endblock %}